### PR TITLE
refactor(*): move config file to `config` directory

### PR DESCRIPTION
**Pull request by radmen**
Files located in `example` dir may be removed by file pruners (such as `yarn autoclean`,
`node-prune`, `mod-clean`). This can lead to fatal error in application.

This PR moves config file from `example` directory to `config`.

### CODE REVIEW

**Review by RomainLanz — APPROVED** [review]

**Comment by RomainLanz** [comment]
Could you please also send a PR to the documentation?
https://github.com/adonisjs/docs/blob/4.0/09-web-security/03-cors.adoc

**Comment by radmen** [comment]
@RomainLanz looks like there's nothing to change.

**Comment by RomainLanz** [comment]
There's a link at the end of this page who point to the config file.

**Comment by radmen** [comment]
Sorry, missed that. I'm sending PR in a moment.

**Comment by radmen** [comment]
Hey, is everything fine with this PR?

**Comment by RomainLanz** [comment]
Yes, let me go ahead and merge this.

**Comment by radmen** [comment]
Thank you! :)

**Pull request merged**
